### PR TITLE
move the regex outside of a list expression.

### PR DESCRIPTION
**Pull request by Nathan-Melaku**
I run into the same issue as described in #2. So this is a simple fix for that.
[Issue](https://github.com/c3lang/c3-ts-mode/issues/2)

### CODE REVIEW

**Comment by lerno** [comment]
@cbuttner do you have time to review this?

**Comment by steeni** [comment]
FWIW I also tried this and it seems to fix the issue. :+1:

**Comment by lerno** [comment]
> FWIW I also tried this and it seems to fix the issue. 👍

Thank you!

**Comment by lerno** [comment]
And thank you for the patch @Nathan-Melaku

**Pull request merged**
